name: docker build
on:
  push:
    branches:
      - main

jobs:
  flaresolverr:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: flaresolverr-dev
      - name: test
        uses: triptixx/action-docker-test@master
        with:
          verbose: true
          repo: flaresolverr-dev
          curl: :8191
      - name: publish
        uses: triptixx/action-docker-publish@master
        with:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          from: flaresolverr-dev
          repo: ${{ secrets.docker_username }}/flaresolverr
          tags: latest,%label org.label-schema.version | %auto
      - name: docker-scout
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ secrets.docker_username }}
          dockerhub-password: ${{ secrets.docker_password }}
          command: cves
          image: ${{ secrets.docker_username }}/flaresolverr:latest
