name: docker build
on:
  push:
    branches:
      - main

jobs:
  flaresolverr:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master
      - name: build
        uses: triptixx/action-docker-build@master
        with:
          repo: flaresolverr-dev
      - name: test
        uses: triptixx/action-docker-test@master
        with:
          verbose: true
          repo: flaresolverr-dev
          delay: 20
          curl: :8191
      - name: publish
        uses: triptixx/action-docker-publish@master
        with:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
          from: flaresolverr-dev
          repo: ${{ secrets.docker_username }}/flaresolverr
          tags: latest,%label org.label-schema.version | %auto
